FROM multiarch/qemu-user-static as qemu

ARG ARCH=
FROM ${ARCH}debian:bullseye

RUN apt update && \
    apt upgrade -y

RUN apt install -y build-essential
RUN apt install -y fakeroot
RUN apt install -y devscripts
RUN apt install -y equivs
RUN apt install -y sudo
RUN apt install -y curl
RUN apt install -y python
RUN apt install -y lsb-release
RUN apt install -y apt-cudf

RUN apt install -y gosu

RUN addgroup machinekit --gid 1000

RUN useradd -m -u 1000 -g 1000 -o -s /bin/bash machinekit

RUN echo "machinekit ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN apt install -y debian-keyring
RUN apt install -y debian-archive-keyring
RUN apt install -y apt-transport-https

USER machinekit
