name: Build ARMv7 .deb Packages

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: false
        default: 'release'

jobs:
  build-armv7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Docker/bullseye/dockerfile
          platforms: linux/arm/v7
          build-args: |
            DOCKER_PLATFORM=linux/arm/v7
            BASE_IMAGE=arm32v7/debian:bullseye
          load: true
          tags: emc-app:${{ github.event.inputs.build_type || 'release' }}

      - name: Execute package build
        run: |
          docker run --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/machinekit/emca \
            --workdir /machinekit/emca \
            --name temp-container \
            --user root \
            -e TMPDIR=/tmp/.build \
            emc-app:${{ github.event.inputs.build_type || 'release' }} \
            /bin/bash -c "\
              chown -R machinekit:machinekit /machinekit/emca && \
              sudo -u machinekit /bin/bash BuildPKG.sh""

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: emc-debs
          path: ./emca/*.deb
